version: '2'

services:
  nextcloud-db:
    image: mariadb
    volumes:
      - ${NEXTCLOUD_DATA}/nextcloud/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}

  nextcloud:
    image: wonderfall/nextcloud
    restart: always
    links:
      - nextcloud-db
    environment:
      - UID=1001
      - GID=1001
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - REDIS_MAX_MEMORY=64mb
      - CRON_PERIOD=15m
      - TZ=America/Chicago
      - ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - DOMAIN=${NEXTCLOUD_DOMAIN}
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=${MYSQL_USER_PASSWORD}
      - DB_HOST=nextcloud-db
    depends_on:
      - nextcloud-db
    volumes:
      - ${NEXTCLOUD_DATA}/nextcloud/data:/data
      - ${NEXTCLOUD_DATA}/nextcloud/config:/config
      - ${NEXTCLOUD_DATA}/nextcloud/apps2:/apps2
      - ${NEXTCLOUD_DATA}/nextcloud/themes:/nextcloud/themes

  collabora:
    image: collabora/code
    restart: always
    environment:
      - domain=${COLLABORA_DOMAIN}
    depends_on:
      - nextcloud-db
    cap_add:
      - MKNOD

  nginx:
    image: nginx
    links:
      - nextcloud
      - collabora
    restart: always
    depends_on:
      - nextcloud
    volumes:
      - ${NEXTCLOUD_DATA}/nginx/letsencrypt:/etc/letsencrypt
      - ${NEXTCLOUD_CONFIG}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
